name: AppLand
on: push

jobs:
  badge_job:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - name: AppLand Badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: time
          LABEL: 'AppLand'
          STATUS: 'https://app.land/applications/165?mapset=2057'
          COLOR: 00EEFF